### ISSUE TITLE
How to use --max-cores and --max-ram parameters

### ISSUE THREAD

**Issue by michael-kotliar** [Duke-GCB/calrissian#103]
Hello,
In the Readme you mentioned that I need to provide the `--max-cores` and `--max-ram` parameters.
> When running calrissian, you must provide a limit the the number of CPU cores (--max-cores) and RAM megabytes (--max-ram) to use concurrently

How exactly are these parameters going to be used? Isn't Kubernetes supposed to manage such parameters by itself based on requested by POD and available on the Node(s) resources?

Thank you

**Comment by dleehr** [comment]
They're used by calrissian for limiting what it will submit to Kubernetes concurrently. 

If, for example, your cluster has 1000GB RAM and 100 CPUs, but you want to limit a single workflow execution to 500GB and 50 CPUs, you could use this parameter to prevent calrissian from using more than 500/50 at a time.

In practice, if you set this limit to higher than your cluster size, workflows will still run, but Kubernetes will queue up tasks after calrissian submits them.

Ideally, the cluster would provide the partitioning and priorities to make this more streamlined. Features such as [multi-tenancy](https://github.com/kubernetes-sigs/multi-tenancy), priorities, and others are still working through SIGs. 

For now, we simply require a user-provided limit :)

**Comment by michael-kotliar** [comment]
Ok, thank you for your answer)
