### ISSUE TITLE
tmp_out directory not readable

### ISSUE THREAD

**Issue by emmanuelmathot** [Duke-GCB/calrissian#110]
## Issue

When running workflows with commandLineTool nodes using heterogeneous dockers executing different users (uid and gid different from calrissian pod executor) and passing files or directories between those nodes, the mounted diirectory from the `tmpout` colume is in read/write access only for the calrissian user.

```console
calrissian@wf-2455d3aa-6d08-11eb-93fa-0a580a8004bc-rfp8q-debug:/workflow/tmpout/wf-2455d3aa-6d08-11eb-93fa-0a580a8004bc$ ls -l
total 0
drwx--S---. 2 calrissian 2012   6 Feb 12 08:00 0saglcsr
drwx--S---. 2 calrissian 2012   6 Feb 12 07:59 _tjo5q72
drwx--S---. 2 calrissian 2012   6 Feb 12 07:59 g8t1xgb8
drwx--S---. 2 calrissian 2012   6 Feb 12 08:00 gu9d3f1e
drwx--S---. 3 calrissian 2012 117 Feb 12 07:59 iwag10jf
drwx--S---. 2 calrissian 2012   6 Feb 12 07:59 sqf02xft
drwx--S---. 2 calrissian 2012   6 Feb 12 07:59 v3dq7qkc
drwx--S---. 2 calrissian 2012   6 Feb 12 08:00 v5o94ty8
drwx--S---. 2 calrissian 2012   6 Feb 12 08:00 vfaque_q
drwx--S---. 3 calrissian 2012 117 Feb 12 08:00 xfdbqqe8
```

Therefore, when a different user id tries to access any files or directories mounted by this `tmpout` volume, it gets a permission denied.

```console
[step-1-pod-ildmppmq] 
[step-1-pod-ildmppmq] Error: Invalid value for '--input_path' / '-i': Path '/var/lib/cwl/stgefa32306-d83c-4541-bb3f-49f976820446/pu3kcpp8' is not readable.
[step-1-pod-ildmppmq] follow_logs end
Handling terminated pod name step-1-pod-ildmppmq with id 2540a277-6ca1-11eb-9ef3-f66950cf5e73
handling completion with 2
PodMonitor removing step-1-pod-ildmppmq
```

I didi not find out where this folder is made and it's permission adjusted. I think this is done by cwltool in the `ensure_non_writable` [function](https://github.com/common-workflow-language/cwltool/blob/07ebbea2bdf97955060c1dd563580b386388519b/cwltool/utils.py#L469) but I could not debug that deep.

In calrissian, I found an entry point for handling this directory in the `add_file_or_directory_volume` [function](https://github.com/Duke-GCB/calrissian/blob/master/calrissian/job.py#L524) where the permission could be granted for other users

## Context

- Openshift 3.11
- GlusterFS dynamic pv provisioning

## Solution

PR https://github.com/Duke-GCB/calrissian/pull/111

**Comment by johnbradley** [comment]
@emmanuelmathot Do you have an example CWL workflow that has this problem? Or does this problem occur for all CWL workflows in your environment?

**Comment by emmanuelmathot** [comment]
*Sorry for the very late reply.*
I link a github gist with the stage-in and cwl job to reproduce the error
