### ISSUE TITLE
nodeSelector for pods spawned by calrissian

### ISSUE THREAD

**Issue by fabricebrito** [Duke-GCB/calrissian#126]
**Current behavior**

Calrissian pod template (https://github.com/Duke-GCB/calrissian/blob/0.10.0/calrissian/job.py#L315) does not allow defining the `nodeSelector` element and thus spawns pods using all nodes in the cluster. 

**Desired behavior**

Allowing settting the key=value elements of the `nodeSelector` element would allow selecting the nodes where Calrissian can spawn pods. 

Reference: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by emmanuelmathot** [comment]
fixed with PR#129
