### ISSUE TITLE
automatically update docker container

### ISSUE THREAD

**Issue by AriBad** [Duke-GCB/calrissian#130]
Hi, I use Calrissian to run a cwl pipeline with cwl v 1.2 on Kubernetes. In order to use cwl v 1.2 I have to use Calrissian version 0.10.0 but the corresponding tag is not available on Docker Hub. The only versions are dukegcb/calrissian:latest or  dukegcb/calrissian:0.9.0.  Is it possible to update the repository to use the latest release of Calrissian with Docker?

Thank you,
Ariane

**Comment by johnbradley** [comment]
Hi @AriBad. Thanks for the issue. I manually built and pushed `dukegcb/calrissian:0.10.0 `. Previously docker hub was automatically building, but they discontinued that service. I'll keep this issue open to track automating the build again (perhaps using github actions).

**Comment by AriBad** [comment]
Thank you very much !
