### ISSUE TITLE
Conditional execution support

### ISSUE THREAD

**Issue by yogeshVU** [Duke-GCB/calrissian#133]
Hi Team,

Does the calrissian support conditional execution?
https://www.commonwl.org/v1.2/Workflow.html#Conditional_execution_(Optional)

thanks,

**Comment by yogeshVU** [comment]
Any updates on this ? Thanks

**Comment by johnbradley** [comment]
@yogeshVU calrissian is built on top of https://github.com/common-workflow-language/cwltool which does support conditionals. I haven't used conditionals with calrissian, but I can't think of any reason why it shouldn't work. Have you encountered a bug trying to use conditionals?

**Comment by emmanuelmathot** [comment]
On our side, we never encountered issues using conditional execution.
