### ISSUE TITLE
docker image migration from docker.com

### ISSUE THREAD

**Issue by emmanuelmathot** [Duke-GCB/calrissian#143]
Following the sunsetting of the public repository at docker.com, 
![image](https://user-images.githubusercontent.com/1178857/225553541-1d5e2209-e304-4c2b-be7b-86d1a6680421.png)

this issue aims at moving the following public images to github registry (ghcr.io) pretty soon

**Comment by hlapp** [comment]
Note that there is an option to apply to the Docker Sponsored Open Source (DSOS) program. The application is very painless, and (at least in my experience for straightforward cases) is processed quite promptly. If approved, the Docker Hub organization on whose behalf you apply in essence gets the fees waived.
[privatereposfaq.pdf](https://github.com/Duke-GCB/calrissian/files/10993911/privatereposfaq.pdf)
