### ISSUE TITLE
Aging dependencies and Python 3.7

### ISSUE THREAD

**Issue by fabricebrito** [Duke-GCB/calrissian#160]
Calrissian relies on Python 3.7 and old pinned dependencies.

* support newer Python versions
* support higher versions for the dependencies

**Comment by fabricebrito** [comment]
@mr-c do you have any hints on why this test https://github.com/Duke-GCB/calrissian/blob/issue-160/tests/test_job.py#L46 is failing with an update of the dependency `shellescape==3.8.1` (`instead of shellescape==3.4.1`? 
It uses `needs_shell_quoting_re = re.compile(r"""(^$|[\s|&;()<>\'"$@])""")` from cwltool's job.py

**Comment by mr-c** [comment]
> @mr-c do you have any hints on why this test https://github.com/Duke-GCB/calrissian/blob/issue-160/tests/test_job.py#L46 is failing with an update of the dependency `shellescape==3.8.1` (`instead of shellescape==3.4.1`? It uses `needs_shell_quoting_re = re.compile(r"""(^$|[\s|&;()<>\'"$@])""")` from cwltool's job.py

I don't, no.

That's the versions we've been testing with: https://github.com/common-workflow-language/cwltool/actions/runs/6932721232/job/18861573891?pr=1938#step:7:168
