### ISSUE TITLE
Get the execution nodes logs

### ISSUE THREAD

**Issue by bjgiraudon** [Duke-GCB/calrissian#179]
Hi,

I am trying to get the logs from the execution pods (the pods spawned by the Calrissian job.)

Is there an option to do so ?

My current solution is to add labels to these pods and get the logs by using the label, which is cumbersome...

**Comment by fabricebrito** [comment]
@bjgiraudon thanks for using calrissian!

Check this entry https://calrissian-cwl.github.io/how-to/save-tool-logs/ and let me know

**Comment by bjgiraudon** [comment]
Thanks for your help @fabricebrito, it solved my problem! I could not find this part of the documentation by myself.
