### ISSUE TITLE
maintain versions of calrissian

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/calrissian#19]
We should be able to re-run workflows with the same version of calrissian.
To support multiple k8s clouds we will need a central location for storing calrissian images.
For example dockerhub.

**Comment by dleehr** [comment]
calrissian releases are on [PyPI](https://pypi.org/project/calrissian/) and [Docker Hub](https://hub.docker.com/r/dukegcb/calrissian/tags)
