### ISSUE TITLE
Changing the top-level job command to ['python','-m','calrissian.main'... fails to find nodejs

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/calrissian#20]
The current job specification has a command that runs run.sh in bash:

https://github.com/Duke-GCB/calrissian/blob/f121924ba3c84030b166055e0b275586fc53d505/openshift/CalrissianJob-revsort.yaml#L12

And the CWL engine runs just fine.

I attempted to change this command in the YAML to remove the intermediate shell script:

```
command: ["python", "-m", "calrissian.main", "--tmpdir-prefix", "/calrissian/tmptmp/", "--tmp-outdir-prefix", "/calrissian/tmpout", "--outdir", "/calrissian/output-data", "/calrissian/input-data/revsort-array.cwl", "/calrissian/input-data/revsort-array-job.json"]
```

But the CWL process fails:

```
cwltool.sandboxjs.JavascriptException: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim
```

If I debug the failed container, `node` is present and available:

<img width="309" alt="screen shot 2019-01-14 at 11 34 26 am" src="https://user-images.githubusercontent.com/2752599/51126135-61170800-17f0-11e9-888b-282bf9c5cf16.png">

I think this is available to shells but not if the container command is bash. Something to watch out for.

**Comment by dleehr** [comment]
Also tried

```
command: ["sh", "-c"]
args: ["python -m calrissian.main --tmpdir-prefix /calrissian/tmptmp/ --tmp-outdir-prefix /calrissian/tmpout --outdir /calrissian/output-data /calrissian/input-data/revsort-array.cwl /calrissian/input-data/revsort-array-job.json"]
```

without success

**Comment by dleehr** [comment]
Guessing there's some `command` script installed by s2i that's not effective when overriding `command`

**Comment by johnbradley** [comment]
I was able to get it to start with something like this:
````
command: ["bash"]
args: ['-c', 'python -m calrissian.main ...'],
```
Perhaps there is a bash profile or something like that in the s2i image ( /etc/bashrc ) ?

**Comment by dleehr** [comment]
Yep, looks like it needs to be bash to source the bashrc file, which provides the path for node. So now I'm able to format the job as:

```
command: ["/bin/bash", "-c"]
args: ["python -m calrissian.main --tmpdir-prefix /calrissian/tmptmp/ --tmp-outdir-prefix /calrissian/tmpout/ --outdir /calrissian/output-data/ /calrissian/input-data/revsort-array.cwl /calrissian/input-data/revsort-array-job.json"]
```

with success
