### ISSUE TITLE
Reconsider mounting /tmp as a shared PersistentVolumeClaim

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/calrissian#30]
Currently, `/tmp` in each container is mounted from a subPath of a shared PV. So each container would get its own `/tmp` but that would be mounted over a network. As I mentioned in https://github.com/Duke-GCB/calrissian/issues/5#issuecomment-453544054, this is probably counter to what we want and should re-consider.

I suggest in https://github.com/Duke-GCB/calrissian/issues/5#issuecomment-455658504 that `tmp` should simply be mounted as a kubernetes `emptyDir`.

**Comment by dleehr** [comment]
This won't be as simple as I thought.

The current implementation (adapted from cwltool) copies [files](https://github.com/Duke-GCB/calrissian/blob/8223523a4f791978761410c3621848d53a515b35/calrissian/job.py#L361-L384) /[directories](https://github.com/Duke-GCB/calrissian/blob/8223523a4f791978761410c3621848d53a515b35/calrissian/job.py#L386-L419)  into `self.tmpdir` using `shutil.copy()`.

It appears to be implementing the [InitialWorkDirRequirement](https://www.commonwl.org/v1.0/CommandLineTool.html#InitialWorkDirRequirement), which allows for writable disposable copies of files/directories.

When that feature is used, `/tmp` is **not** empty before the container runs, so it wouldn't make sense to replace it with `emptyDir`.

Worth further discussion, won't be implementing anything immediately.

**Comment by dleehr** [comment]
When I was porting this code, the `shutil.copy()` and `tempfile.mkdtemp()` calls jumped out as something that tightly couples the workflow engine to the local filesystem. I added debug logging around those calls to be able to see when it's used.

I think the best solution to this (and also relates to #31) would be to remove that coupling wherever possible. At some level, the engine does need access to the files to calculate checksums and sizes, but I don't think we should be tightening that coupling.

**Comment by dleehr** [comment]
We'll want some data to determine how important this is. While we could (in most cases) just use a node-local /tmp directory from an `emptyDir` volume, that would not work (as stated above) for some CWL features used by other disciplines.

**Comment by dleehr** [comment]
On a recent CWL call, I heard about the genesis of this feature (writable files put into tmp) and that it's for large data sets that need to be mutable but perhaps disposable.

That doesn't come up in our use cases. Again we'd still need some performance data, but I think the best plan for this feature is to default to using a local `emptyDir` for tmp, and if a case arises where that wouldn't work (the shutil.copy lines above), then to either raise an exception or fall back to the current behavior of using the shared PVC tmpdir.

**Comment by dleehr** [comment]
Related to https://github.com/Duke-GCB/lando/issues/141
