### ISSUE TITLE
Errors when not including trailing slash in input tmpdir params

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/calrissian#33]
### --tmp-outdir-prefix
When `--tmp-outdir-prefix /calrissian/tmpout` is used the following error occurs:
```
...
Unhandled error, try again with --debug for more information:
--
  | [Errno 13] Permission denied: '/calrissian/tmpoutocot8g90'
```
I believe this should have been `/calrissian/tmpout/ocot8g90`

### --tmpdir-prefix
When `--tmpdir-prefix /calrissian/tmptmp` is used the following error occurs:
```
Unexpected exception
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/cwltool/workflow.py", line 793, in job
  | runtimeContext):
  | File "/opt/app-root/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 500, in job
  | tempfile.mkdtemp(prefix=tmpdir_prefix)  # type: ignore
  | File "/opt/app-root/lib64/python3.6/tempfile.py", line 368, in mkdtemp
  | _os.mkdir(file, 0o700)
  | PermissionError: [Errno 13] Permission denied: '/calrissian/tmptmp9z0_79if'
  | Cannot make scatter job: [Errno 13] Permission denied: '/calrissian/tmptmp9z0_79if'
  | Workflow cannot make any more progress.
```
I believe this should have been `/calrissian/tmptmp/9z0_79if`

**Comment by dleehr** [comment]
Relevant code in lando:

https://github.com/Duke-GCB/lando/blob/da2c40ef588578993a45c46f20676a691ef68067/lando/k8s/jobmanager.py#L171-L174

**Comment by johnbradley** [comment]
I think this isn't a bug. Users can use these flags to prefix the assoicated directories/files related to these flags. This functionality is inherited from cwltool.
Closing this issue.
