### ISSUE TITLE
Include labels on submitted pods

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/calrissian#38]
It would be nice to be able to query for pods that are part of a workflow by a label/selector.

Add an argument or env var to provide as a prefix or similar, so that we can annotate job IDs and steps as done in lando:

https://github.com/Duke-GCB/lando/blob/f8b661fb6becb00e3f98f866537dba662cc63ebf/lando/k8s/jobmanager.py#L30-L35

**Comment by dleehr** [comment]
@johnbradley I'd like to make this consistent/complementary to what we have in lando. Can you give a couple examples on what those labels will look like in practice?

**Comment by johnbradley** [comment]
In lando we use three labels for lando jobs, config_maps, etc.

### Where we declare and populate them

https://github.com/Duke-GCB/lando/blob/8b280f39dd1e16070491e9524b6386f24707fe34/lando/k8s/jobmanager.py#L10-L21
```
class JobLabels(object):
    BESPIN_JOB = "bespin-job"  # expected value is "true"
    JOB_ID = "bespin-job-id"
    STEP_TYPE = "bespin-job-step"


class JobStepTypes(object):
    STAGE_DATA = "stage_data"
    RUN_WORKFLOW = "run_workflow"
    ORGANIZE_OUTPUT = "organize_output"
    SAVE_OUTPUT = "save_output"
```

https://github.com/Duke-GCB/lando/blob/8b280f39dd1e16070491e9524b6386f24707fe34/lando/k8s/jobmanager.py#L31

```
    def make_job_labels(self, job_step_type):
        return {
            JobLabels.BESPIN_JOB: "true",
            JobLabels.JOB_ID: str(self.job.id),
            JobLabels.STEP_TYPE: job_step_type
        }
```

### Where they get passed to kubernetes
https://github.com/Duke-GCB/lando/blob/8b280f39dd1e16070491e9524b6386f24707fe34/lando/k8s/cluster.py#L232-L237
```
        return client.V1JobSpec(
            template=client.V1PodTemplateSpec(
                metadata=client.V1ObjectMeta(name=job_spec_name, labels=self.labels),
                spec=self.create_pod_spec()
            )
        )
```

The `bespin-job=true` label seems a little odd to me. I thought about something like `service-type=bespin`, but that's another issue/repo.
