### ISSUE TITLE
Support for specifying max ram in kubernetes units

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/calrissian#52]
Calrissian currently has an integer ` --max-ram` flag that specifies the 
> Maximum amount of RAM in MB to use

It would be convenient to specify memory sizing in the same way [kubernetes does](
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory)
So for specifying larger sizes users could just do something like `--max-ram 10Gi`

This would help with https://github.com/Duke-GCB/lando/issues/158

**Comment by dleehr** [comment]
@johnbradley This is now released in 0.3.0
