### ISSUE TITLE
Use the canonical copy of the CWL conformance tests

### ISSUE THREAD

**Issue by mr-c** [Duke-GCB/calrissian#82]
https://github.com/common-workflow-language/common-workflow-language is the canonical location for the CWL v1.0 conformance tests

**Comment by dleehr** [comment]
Thanks @mr-c! I updated to using the [v1.0.1 release](https://github.com/common-workflow-language/common-workflow-language/releases/tag/v1.0.1) on [82-canonical-conformance-tests](https://github.com/Duke-GCB/calrissian/tree/82-canonical-conformance-tests) and have fewer failures now.

https://github.com/Duke-GCB/calrissian/blob/16f78bfd44392ad6237a61525ad4e957e1ed634a/conformance/results.txt#L314-L316

However I only find 2 failures in the [output](https://github.com/Duke-GCB/calrissian/blob/82-canonical-conformance-tests/conformance/results.txt):

I know for example that many of the DockerRequirement features are not supported (#12):

https://github.com/Duke-GCB/calrissian/blob/d60a31dce2e9969c19f113ac2c9522d7d3b68d34/calrissian/job.py#L378-L390

so I would expect this one to fail:

https://github.com/Duke-GCB/calrissian/blob/16f78bfd44392ad6237a61525ad4e957e1ed634a/conformance/results.txt#L282-L284

but it doesn't appear to. Any idea how to root out this or other failures?

I'm using

**Comment by mr-c** [comment]
When a test fails, I re run it manually using the provided command line without `--quiet` and adding engine specific debugging options like `--debug` or similar

**Comment by dleehr** [comment]
> I would expect this one to fail ... but it doesn't appear to. Any idea how to root out this or other failures?

This was caused by using a 2-year old release of https://github.com/common-workflow-language/common-workflow-language. Updating to today's release (v1.0.2) runs a total of 197 tests for 1.0 with 191 passing. And the failures are all accounted for.
